from dataclasses import dataclass
from io import BytesIO

from PIL import Image, ImageDraw, ImageFont

from helpers.config_loader import get_config

ASSETS = "data/assets/image_gen"
EMOJI_ASSETS = "data/assets/emojis"
FONTPATH = f"{ASSETS}/rodinntlg_eb.otf"
FONTPATH_LIGHT = f"{ASSETS}/rodinntlg_m.otf"


@dataclass
class StrDifficultyCategory:
    difficulty: str
    ap_count: int
    fc_count: int
    clear_count: int
    all_count: int


def _draw_gradient(img: Image.Image, start: tuple, end: tuple) -> None:
    draw = ImageDraw.Draw(img)
    h, w = img.height, img.width
    r0, g0, b0 = start[:3]  # getpixel on RGBA sources returns 4-tuples
    r1, g1, b1 = end[:3]
    for y in range(h):
        t = y / h
        draw.line(
            [(0, y), (w, y)],
            fill=(
                int(r0 + (r1 - r0) * t),
                int(g0 + (g1 - g0) * t),
                int(b0 + (b1 - b0) * t),
            ),
        )


def generate_general_progress(data: list[StrDifficultyCategory]) -> BytesIO:
    IMAGE_WIDTH = 2000
    HEADER_HEIGHT = 200
    SUB_HEADER_HEIGHT = 50
    CARD_GUTTER_HEIGHT = 50
    CARD_GUTTER_WIDTH = 50
    CARD_WIDTH = IMAGE_WIDTH - (CARD_GUTTER_WIDTH * 2)

    BADGE_HPAD = 40
    BADGE_VPAD = 20
    badge_font = ImageFont.truetype(FONTPATH, 70)

    DONUT_SIZE = 350
    DONUT_PADDING = 30
    DONUT_THICKNESS = 75

    COUNT_PADDING_Y = 30
    COUNT_PADDING_X = 30
    COUNT_FONT_CATEGORIES = ImageFont.truetype(FONTPATH, 50)
    COUNT_FONT_TEXT = ImageFont.truetype(FONTPATH_LIGHT, 50)
    COUNT_FONT_COLOR = "white"
    line_spacing = 20

    FC_COLOR = "#e83ce3"
    CLEAR_COLOR = "#F9D442"
    NOT_CLEAR_COLOR = "#38383a"
    ICON_PADDING = 20

    difficulty_colors = {
        "append": f"{EMOJI_ASSETS}/append_color.png",
        "hard": f"{EMOJI_ASSETS}/hard_color.png",
        "normal": f"{EMOJI_ASSETS}/normal_color.png",
        "easy": f"{EMOJI_ASSETS}/easy_color.png",
        "master": f"{EMOJI_ASSETS}/master_color.png",
        "expert": f"{EMOJI_ASSETS}/expert_color.png",
    }
    difficulty_images = {
        key: Image.open(path)
        .resize((CARD_WIDTH, DONUT_SIZE), Image.Resampling.LANCZOS)
        .convert("RGBA")
        for key, path in difficulty_colors.items()
    }
    _ICON_CACHE = {
        "ap": Image.open(f"{EMOJI_ASSETS}/normal_ap.png").convert("RGBA"),
        "ap_append": Image.open(f"{EMOJI_ASSETS}/append_ap.png").convert("RGBA"),
        "fc": Image.open(f"{EMOJI_ASSETS}/normal_fc.png").convert("RGBA"),
        "fc_append": Image.open(f"{EMOJI_ASSETS}/append_fc.png").convert("RGBA"),
        "clear": Image.open(f"{EMOJI_ASSETS}/normal_clear.png").convert("RGBA"),
        "clear_append": Image.open(f"{EMOJI_ASSETS}/append_clear.png").convert("RGBA"),
    }

    max_text_width = 0.0
    max_text_height = 0
    for diff in data:
        text = diff.difficulty.upper() + "hi"
        max_text_width = max(max_text_width, badge_font.getlength(text))
        bbox = badge_font.getbbox(text)
        max_text_height = max(max_text_height, int(bbox[3] - bbox[1]))
    max_badge_width = int(max_text_width + 2 * BADGE_HPAD)
    max_badge_height = int(max_text_height + 2 * BADGE_VPAD)

    bbox = COUNT_FONT_CATEGORIES.getbbox("ALL PERFECT")
    text_height = int(bbox[3] - bbox[1])
    counts_panel_height = (
        COUNT_PADDING_Y + (text_height * 4) + (line_spacing * 3) + COUNT_PADDING_Y
    )
    row_height = max(DONUT_SIZE, counts_panel_height)
    white_card_padding = 30
    CARD_CONTENT_HEIGHT = row_height + (white_card_padding * 2)
    CARD_CONTAINER_HEIGHT = CARD_CONTENT_HEIGHT + (max_badge_height // 2)
    number_of_cards = len(data)
    total_height = (
        HEADER_HEIGHT
        + SUB_HEADER_HEIGHT
        + (number_of_cards * CARD_CONTAINER_HEIGHT)
        + ((number_of_cards + 1) * CARD_GUTTER_HEIGHT)
    )

    new_im = Image.new("RGBA", (IMAGE_WIDTH, total_height))
    background_img = Image.open(f"{ASSETS}/hug.png")
    ow, oh = background_img.size
    if oh > total_height:
        background_img = background_img.crop((0, 0, ow, total_height))
    else:
        background_img = background_img.resize((ow, total_height))
    background_img = background_img.resize((IMAGE_WIDTH, total_height))
    new_im.paste(background_img, (0, 0))

    im_draw = ImageDraw.Draw(new_im)
    im_draw.rectangle(
        [(0, 0), (new_im.width, HEADER_HEIGHT)], fill="#b4ccfa", outline="#00194a"
    )
    im_draw.text(
        (20, 28),
        "Your PJSK All Difficulty Summary",
        fill="black",
        font=ImageFont.truetype(FONTPATH, 96),
    )
    im_draw.text(
        (20, 130),
        f"Generated by {get_config()['discord']['name']}",
        fill="black",
        font=ImageFont.truetype(FONTPATH, 60),
    )

    for i, diff in enumerate(data):
        y_card = (
            HEADER_HEIGHT
            + SUB_HEADER_HEIGHT
            + CARD_GUTTER_HEIGHT
            + i * (CARD_CONTAINER_HEIGHT + CARD_GUTTER_HEIGHT)
        )
        card_container = Image.new(
            "RGBA", (CARD_WIDTH, CARD_CONTAINER_HEIGHT), (255, 255, 255, 0)
        )
        container_draw = ImageDraw.Draw(card_container)
        CARD_RADIUS = 25
        container_draw.rounded_rectangle(
            (
                white_card_padding,
                white_card_padding,
                CARD_WIDTH - white_card_padding,
                CARD_CONTAINER_HEIGHT - white_card_padding,
            ),
            radius=CARD_RADIUS,
            fill="white",
        )

        content_area_x = white_card_padding
        content_area_y = white_card_padding
        content_area_width = CARD_WIDTH - 2 * white_card_padding
        content_area_height = CARD_CONTAINER_HEIGHT - 2 * white_card_padding
        donut_x = content_area_x + DONUT_PADDING
        donut_y = content_area_y + (content_area_height - DONUT_SIZE) // 2

        donut_img = Image.new("RGBA", (DONUT_SIZE, DONUT_SIZE), (255, 255, 255, 0))
        donut_draw = ImageDraw.Draw(donut_img)
        aped = diff.ap_count
        fced = diff.fc_count - diff.ap_count
        cleared = diff.clear_count - diff.fc_count
        not_cleared = diff.all_count - diff.clear_count
        total = diff.all_count or 1
        angle_ap = (aped / total) * 360
        angle_fc = angle_ap + (fced / total) * 360
        angle_clear = angle_fc + (cleared / total) * 360
        angle_not_clear = angle_clear + (not_cleared / total) * 360
        pie_location = (0, 0, DONUT_SIZE, DONUT_SIZE)
        donut_draw.pieslice(pie_location, 0, 360, fill="white")

        ap_color_sample = _ICON_CACHE["ap"]
        w_s, h_s = ap_color_sample.size
        color_top = ap_color_sample.getpixel((w_s // 2, min(60, h_s - 1)))
        color_bottom = ap_color_sample.getpixel((w_s // 2, max(h_s - 60, 0)))
        gradient = Image.new("RGB", (DONUT_SIZE, DONUT_SIZE))
        _draw_gradient(gradient, color_top, color_bottom)  # type: ignore[arg-type]
        im_mask = Image.new("L", (DONUT_SIZE, DONUT_SIZE), 0)
        ImageDraw.Draw(im_mask).pieslice(
            (0, 0, DONUT_SIZE, DONUT_SIZE), 0, angle_ap, fill=255
        )
        donut_img.paste(gradient, (0, 0), im_mask)

        donut_draw.pieslice(pie_location, angle_ap, angle_fc, fill=FC_COLOR)
        donut_draw.pieslice(pie_location, angle_fc, angle_clear, fill=CLEAR_COLOR)
        donut_draw.pieslice(
            pie_location, angle_clear, angle_not_clear, fill=NOT_CLEAR_COLOR
        )
        donut_draw.ellipse(
            (
                DONUT_THICKNESS,
                DONUT_THICKNESS,
                DONUT_SIZE - DONUT_THICKNESS,
                DONUT_SIZE - DONUT_THICKNESS,
            ),
            fill="white",
        )

        icon_size = DONUT_SIZE - (DONUT_THICKNESS * 2) - (ICON_PADDING * 2)
        icon_xy = ((DONUT_SIZE - icon_size) // 2, (DONUT_SIZE - icon_size) // 2)
        is_append = diff.difficulty.lower() == "append"
        if diff.ap_count == diff.all_count:
            icon = _ICON_CACHE["ap_append" if is_append else "ap"].resize(
                (icon_size, icon_size)
            )
            donut_img.paste(icon, icon_xy, icon)
        elif diff.fc_count == diff.all_count:
            icon = _ICON_CACHE["fc_append" if is_append else "fc"].resize(
                (icon_size, icon_size)
            )
            donut_img.paste(icon, icon_xy, icon)
        elif diff.clear_count == diff.all_count:
            icon = _ICON_CACHE["clear_append" if is_append else "clear"].resize(
                (icon_size, icon_size)
            )
            donut_img.paste(icon, icon_xy, icon)

        card_container.paste(donut_img, (donut_x, donut_y), donut_img)

        count_panel_x = donut_x + DONUT_SIZE + DONUT_PADDING
        content_area_right = content_area_x + content_area_width
        count_panel_width = content_area_right - count_panel_x - DONUT_PADDING
        count_img = Image.new(
            "RGBA", (count_panel_width, DONUT_SIZE), (255, 255, 255, 0)
        )
        count_draw = ImageDraw.Draw(count_img)
        count_draw.rounded_rectangle(
            (0, 0, count_panel_width, DONUT_SIZE), radius=CARD_RADIUS, fill="#38383adf"
        )
        labels = ["ALL PERFECT", "FULL COMBO", "CLEAR", "ALL"]
        values = [diff.ap_count, diff.fc_count, diff.clear_count, diff.all_count]
        total_text_height = (text_height * 4) + (line_spacing * 3)
        start_y = (DONUT_SIZE - total_text_height) // 2
        for idx, (label, value) in enumerate(zip(labels, values)):
            y_pos = start_y + idx * (text_height + line_spacing)
            count_draw.text(
                (COUNT_PADDING_X, y_pos),
                label,
                fill=COUNT_FONT_COLOR,
                font=COUNT_FONT_CATEGORIES,
            )
            count_draw.text(
                (count_panel_width - COUNT_PADDING_X, y_pos),
                str(value),
                fill=COUNT_FONT_COLOR,
                font=COUNT_FONT_TEXT,
                anchor="ra",
            )
        card_container.alpha_composite(count_img, (count_panel_x, donut_y))
        new_im.alpha_composite(card_container, (CARD_GUTTER_WIDTH, y_card))

        base_img = difficulty_images.get(diff.difficulty.lower())
        if base_img and diff.difficulty.lower() == "append":
            top_color = base_img.getpixel((1, 1))
            bottom_color = base_img.getpixel((CARD_WIDTH - 1, DONUT_SIZE - 1))
            badge_bg = Image.new("RGB", (max_badge_width, max_badge_height))
            _draw_gradient(badge_bg, top_color, bottom_color)  # type: ignore[arg-type]
        elif base_img:
            badge_bg = Image.new(
                "RGB", (max_badge_width, max_badge_height), base_img.getpixel((1, 1))
            )
        else:
            badge_bg = Image.new("RGB", (max_badge_width, max_badge_height), "gray")
        badge_mask = Image.new("L", (max_badge_width, max_badge_height), 0)
        ImageDraw.Draw(badge_mask).rounded_rectangle(
            (0, 0, max_badge_width, max_badge_height),
            radius=(max_badge_height // 2),
            fill=255,
        )
        badge_x = CARD_GUTTER_WIDTH + (CARD_WIDTH - max_badge_width) // 2
        badge_y = y_card - 20
        new_im.paste(badge_bg, (badge_x, badge_y), badge_mask)
        badge_text = diff.difficulty.upper()
        text_w = badge_font.getlength(badge_text)
        text_bbox = badge_font.getbbox(badge_text)
        text_h = text_bbox[3] - text_bbox[1]
        im_draw.text(
            (
                badge_x + (max_badge_width - text_w) / 2,
                badge_y + (max_badge_height - text_h) / 2 - 5,
            ),
            badge_text,
            fill="black",
            font=badge_font,
        )

    obj = BytesIO()
    new_im.save(obj, "PNG")
    obj.seek(0)
    return obj
